### ISSUE TITLE
License

### ISSUE THREAD

**Issue by larshp** [christianguenter2/ABAP_conways_game_of_life#1]
Hi,
Can you help adding a license to let users know how/if they can use the code?

See
https://help.github.com/articles/adding-a-license-to-a-repository/
https://choosealicense.com/

**Comment by christianguenter2** [comment]
Sure, added the license

**Comment by larshp** [comment]
make sure to merge the branch, https://github.com/christianguenter2/ABAP_conways_game_of_life/tree/add-license-1

**Comment by christianguenter2** [comment]
merged
